# See https://rust-lang.github.io/rustfmt/ for details on the options.
unstable_features = true

imports_granularity = "Crate"
group_imports = "One"

normalize_comments = true
wrap_comments = true
comment_width = 100       # Same as the default value of `max_width`.

hex_literal_case = "Lower"
condense_wildcard_suffixes = true
use_field_init_shorthand = true
use_try_shorthand = true
reorder_impl_items = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
